language: python
sudo: required
python:
  - "3.6.4"

services:
  - docker

install:
  - pip install mypy
  - pip install mypy_extensions
  - pip install xml2rfc
  - pip install typeguard
  - gem install --no-doc kramdown-rfc2629

jobs:
  include:
    - stage: build
      name: python build
      script:
        - make -C build test
    - stage: docs
      name: rfc
      script:
        - make -C rfc
    - stage: "test & typecheck"
      name: run
      script: make run
    -
      name: checkspec
      script: make check
    -
      name: test typechecked
      script: make test
    # Typecheck slow specs.
    -
      name: test kyber
      script: make kyber-test
    # WOTS is way too slow for travis :(
    # -
    #   name: test wots
    #   script: make wots-test
    -
      name: test argon2i
      script: make argon2i-test
    # Run OCaml compiler and FStar compilation in docker.
    -
      name: compiler
      install: skip
      script:
        - docker run -v $PWD:/home/worker/_hacspec --rm -ti franziskus/hacspec:0.2 /home/worker/_hacspec/docker/travis-compiler/run.sh
