language: python
sudo: required
python:
  - "3.6.4"

install:
  - pip install mypy
  - pip install mypy_extensions
  - pip install xml2rfc
  - pip install typeguard
  - gem install --no-doc kramdown-rfc2629

jobs:
  include:
    - stage: build
      script:
        - make -C build test
    - stage: test
      script: make run
    -
      script: make check
    -
      script: make test
    - stage: compilers
      script:
        - docker run -v $PWD:/home/worker/hacspec --rm -ti franziskus/hacspec:0.1 make -C hacspec/spec-checker-ocaml
    - stage: docs
      script:
        - make -C rfc
