language: python
python:
  - "3.6"

install:
  - pip install mypy
  - pip install mypy_extensions
  - pip install xml2rfc
  - pip install typeguard
  - gem install --no-doc kramdown-rfc2629

script:
  # - make -C build test
  - make # travis_wait 40
  - make -C spec-compilers
  - make -C rfc
